config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :books
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true,
                    length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end
  
  
  def show
    @book = Book.find(params[:id])
  end
 
  
  def new
  end
  
  
  
  def create

    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end

  end
    
  
  private
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :ISBN, :description)
    end  
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<h1>Listing books</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
  </tr>
 
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
    </tr>
  <% end %>
</table>
<br><br>

<%= link_to 'Add a new book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_for :book, url: books_path do |f| %>
 


  <% if @book.errors.any? %>
    <div id="error_explanation" style="color:red">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 




  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </p>

  <p>
    <%= f.label :ISBN %><br>
    <%= f.number_field :ISBN %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
 

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>
 

<p>
  <strong>ISBN:</strong>
  <%= @book.ISBN %>
</p>
 

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>



<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSwap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Running Rails</h1>


<%= link_to 'Books', controller: 'books' %>
<br><br>
<%= link_to 'Add a new book', new_book_path %>
 